## @file
# Template file used to generate tags on ADO.
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

parameters:
  - name: base_version
    displayName: Path to the devops directory.
    type: string
    default: ""
  - name: git_name
    displayName: Name to use for creating tag.
    type: string
    default: ""
  - name: git_email
    displayName: Email to use for creating tag.
    type: string
    default: ""

jobs:
  - job: Create_Release_Tag
    steps:
      - checkout: self
        clean: true
        fetchTags: true
        persistCredentials: true
        path: "target"

      - checkout: mu_devops
        path: "mu_devops"
        fetchDepth: 0

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.10"
        displayName: "Setup Python"

      - script: |
          python -m pip install --upgrade pip
          pip install GitPython
        displayName: "Install Dependencies"

      - script: |
          git config --global user.name "${{ parameters.git_name }}"
          git config --global user.email "${{ parameters.git_email }}"
          ls $(Agent.BuildDirectory)
        displayName: "Setup Git"

      - script: |
          cd $(Agent.BuildDirectory)
          python mu_devops/Scripts/TagGenerator.py -r target/ -b ${{ parameters.base_version }} -v --tagvar tag_name --notes target/ReleaseNotes.md --url $(Build.Repository.Uri)
        displayName: "Run Tag Generator"

      - script: |
          cd $(Agent.BuildDirectory)/target
          git branch
          git add ReleaseNotes.md
          git commit -m "Release notes for $(tag_name)"
          git tag $(tag_name)
        displayName: "Create Tag"

      - script: |
          cd $(Agent.BuildDirectory)/target
          git push origin HEAD:$(Build.SourceBranchName)
        displayName: "Push Commit"

      - script: |
          cd $(Agent.BuildDirectory)/target
          git push origin $(tag_name)
        displayName: "Push Tag"
